
let debug = false

let initialState = {
    currentPage: "Upload",
    parsedData: undefined,
    parsedMeta: undefined,
    variableOnXaxis:     undefined,
    variableOnYaxis:     undefined,
    variableOnColorAxis: undefined,
    showDistribution: false
}

if (debug) {
    // To save redux state while running the app:
    // - console.log the state from source code
    // - right click in console and "Save as global variable"
    // - copy(temp1) in console
    // - paste here
    initialState = {
      "currentPage": "Home",
      "parsedData": [
        {
          "Id passeggero": 1,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Braund, Mr. Owen Harris",
          "Sesso": "male",
          "Età": 22,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": "A/5 21171",
          "Prezzo": 7.25,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 2,
          "Sopravvissuto": 1,
          "Classe": 1,
          "Nome": "Cumings, Mrs. John Bradley (Florence Briggs Thayer)",
          "Sesso": "female",
          "Età": 38,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": "PC 17599",
          "Prezzo": 71.2833,
          "Cabina": "C85",
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 3,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "Heikkinen, Miss. Laina",
          "Sesso": "female",
          "Età": 26,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": "STON/O2. 3101282",
          "Prezzo": 7.925,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 4,
          "Sopravvissuto": 1,
          "Classe": 1,
          "Nome": "Futrelle, Mrs. Jacques Heath (Lily May Peel)",
          "Sesso": "female",
          "Età": 35,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": 113803,
          "Prezzo": 53.1,
          "Cabina": "C123",
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 5,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Allen, Mr. William Henry",
          "Sesso": "male",
          "Età": 35,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 373450,
          "Prezzo": 8.05,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 6,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Moran, Mr. James",
          "Sesso": "male",
          "Età": null,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 330877,
          "Prezzo": 8.4583,
          "Cabina": null,
          "Imbarcato": "Q"
        },
        {
          "Id passeggero": 7,
          "Sopravvissuto": 0,
          "Classe": 1,
          "Nome": "McCarthy, Mr. Timothy J",
          "Sesso": "male",
          "Età": 54,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 17463,
          "Prezzo": 51.8625,
          "Cabina": "E46",
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 8,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Palsson, Master. Gosta Leonard",
          "Sesso": "male",
          "Età": 2,
          "Parenti a bordo": 4,
          "Fratelli o consorti a bordo": 3,
          "Genitori o figli a bordo": 1,
          "Biglietto": 349909,
          "Prezzo": 21.075,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 9,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",
          "Sesso": "female",
          "Età": 27,
          "Parenti a bordo": 2,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 2,
          "Biglietto": 347742,
          "Prezzo": 11.1333,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 10,
          "Sopravvissuto": 1,
          "Classe": 2,
          "Nome": "Nasser, Mrs. Nicholas (Adele Achem)",
          "Sesso": "female",
          "Età": 14,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": 237736,
          "Prezzo": 30.0708,
          "Cabina": null,
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 11,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "Sandstrom, Miss. Marguerite Rut",
          "Sesso": "female",
          "Età": 4,
          "Parenti a bordo": 2,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 1,
          "Biglietto": "PP 9549",
          "Prezzo": 16.7,
          "Cabina": "G6",
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 12,
          "Sopravvissuto": 1,
          "Classe": 1,
          "Nome": "Bonnell, Miss. Elizabeth",
          "Sesso": "female",
          "Età": 58,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 113783,
          "Prezzo": 26.55,
          "Cabina": "C103",
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 13,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Saundercock, Mr. William Henry",
          "Sesso": "male",
          "Età": 20,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": "A/5. 2151",
          "Prezzo": 8.05,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 14,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Andersson, Mr. Anders Johan",
          "Sesso": "male",
          "Età": 39,
          "Parenti a bordo": 6,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 5,
          "Biglietto": 347082,
          "Prezzo": 31.275,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 15,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Vestrom, Miss. Hulda Amanda Adolfina",
          "Sesso": "female",
          "Età": 14,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 350406,
          "Prezzo": 7.8542,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 16,
          "Sopravvissuto": 1,
          "Classe": 2,
          "Nome": "Hewlett, Mrs. (Mary D Kingcome) ",
          "Sesso": "female",
          "Età": 55,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 248706,
          "Prezzo": 16,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 17,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Rice, Master. Eugene",
          "Sesso": "male",
          "Età": 2,
          "Parenti a bordo": 5,
          "Fratelli o consorti a bordo": 4,
          "Genitori o figli a bordo": 1,
          "Biglietto": 382652,
          "Prezzo": 29.125,
          "Cabina": null,
          "Imbarcato": "Q"
        },
        {
          "Id passeggero": 18,
          "Sopravvissuto": 1,
          "Classe": 2,
          "Nome": "Williams, Mr. Charles Eugene",
          "Sesso": "male",
          "Età": null,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 244373,
          "Prezzo": 13,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 19,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)",
          "Sesso": "female",
          "Età": 31,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": 345763,
          "Prezzo": 18,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 20,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "Masselmani, Mrs. Fatima",
          "Sesso": "female",
          "Età": null,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 2649,
          "Prezzo": 7.225,
          "Cabina": null,
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 21,
          "Sopravvissuto": 0,
          "Classe": 2,
          "Nome": "Fynney, Mr. Joseph J",
          "Sesso": "male",
          "Età": 35,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 239865,
          "Prezzo": 26,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 22,
          "Sopravvissuto": 1,
          "Classe": 2,
          "Nome": "Beesley, Mr. Lawrence",
          "Sesso": "male",
          "Età": 34,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 248698,
          "Prezzo": 13,
          "Cabina": "D56",
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 23,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "McGowan, Miss. Anna \"Annie\"",
          "Sesso": "female",
          "Età": 15,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 330923,
          "Prezzo": 8.0292,
          "Cabina": null,
          "Imbarcato": "Q"
        },
        {
          "Id passeggero": 24,
          "Sopravvissuto": 1,
          "Classe": 1,
          "Nome": "Sloper, Mr. William Thompson",
          "Sesso": "male",
          "Età": 28,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 113788,
          "Prezzo": 35.5,
          "Cabina": "A6",
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 25,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Palsson, Miss. Torborg Danira",
          "Sesso": "female",
          "Età": 8,
          "Parenti a bordo": 4,
          "Fratelli o consorti a bordo": 3,
          "Genitori o figli a bordo": 1,
          "Biglietto": 349909,
          "Prezzo": 21.075,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 26,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)",
          "Sesso": "female",
          "Età": 38,
          "Parenti a bordo": 6,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 5,
          "Biglietto": 347077,
          "Prezzo": 31.3875,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 27,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Emir, Mr. Farred Chehab",
          "Sesso": "male",
          "Età": null,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 2631,
          "Prezzo": 7.225,
          "Cabina": null,
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 28,
          "Sopravvissuto": 0,
          "Classe": 1,
          "Nome": "Fortune, Mr. Charles Alexander",
          "Sesso": "male",
          "Età": 19,
          "Parenti a bordo": 5,
          "Fratelli o consorti a bordo": 3,
          "Genitori o figli a bordo": 2,
          "Biglietto": 19950,
          "Prezzo": 263,
          "Cabina": "C23 C25 C27",
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 29,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "O'Dwyer, Miss. Ellen \"Nellie\"",
          "Sesso": "female",
          "Età": null,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 330959,
          "Prezzo": 7.8792,
          "Cabina": null,
          "Imbarcato": "Q"
        },
        {
          "Id passeggero": 30,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Todoroff, Mr. Lalio",
          "Sesso": "male",
          "Età": null,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 349216,
          "Prezzo": 7.8958,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 31,
          "Sopravvissuto": 0,
          "Classe": 1,
          "Nome": "Uruchurtu, Don. Manuel E",
          "Sesso": "male",
          "Età": 40,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": "PC 17601",
          "Prezzo": 27.7208,
          "Cabina": null,
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 32,
          "Sopravvissuto": 1,
          "Classe": 1,
          "Nome": "Spencer, Mrs. William Augustus (Marie Eugenie)",
          "Sesso": "female",
          "Età": null,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": "PC 17569",
          "Prezzo": 146.5208,
          "Cabina": "B78",
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 33,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "Glynn, Miss. Mary Agatha",
          "Sesso": "female",
          "Età": null,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 335677,
          "Prezzo": 7.75,
          "Cabina": null,
          "Imbarcato": "Q"
        },
        {
          "Id passeggero": 34,
          "Sopravvissuto": 0,
          "Classe": 2,
          "Nome": "Wheadon, Mr. Edward H",
          "Sesso": "male",
          "Età": 66,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": "C.A. 24579",
          "Prezzo": 10.5,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 35,
          "Sopravvissuto": 0,
          "Classe": 1,
          "Nome": "Meyer, Mr. Edgar Joseph",
          "Sesso": "male",
          "Età": 28,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": "PC 17604",
          "Prezzo": 82.1708,
          "Cabina": null,
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 36,
          "Sopravvissuto": 0,
          "Classe": 1,
          "Nome": "Holverson, Mr. Alexander Oskar",
          "Sesso": "male",
          "Età": 42,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": 113789,
          "Prezzo": 52,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 37,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "Mamee, Mr. Hanna",
          "Sesso": "male",
          "Età": null,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 2677,
          "Prezzo": 7.2292,
          "Cabina": null,
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 38,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Cann, Mr. Ernest Charles",
          "Sesso": "male",
          "Età": 21,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": "A./5. 2152",
          "Prezzo": 8.05,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 39,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Vander Planke, Miss. Augusta Maria",
          "Sesso": "female",
          "Età": 18,
          "Parenti a bordo": 2,
          "Fratelli o consorti a bordo": 2,
          "Genitori o figli a bordo": 0,
          "Biglietto": 345764,
          "Prezzo": 18,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 40,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "Nicola-Yarred, Miss. Jamila",
          "Sesso": "female",
          "Età": 14,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": 2651,
          "Prezzo": 11.2417,
          "Cabina": null,
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 41,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",
          "Sesso": "female",
          "Età": 40,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": 7546,
          "Prezzo": 9.475,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 42,
          "Sopravvissuto": 0,
          "Classe": 2,
          "Nome": "Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)",
          "Sesso": "female",
          "Età": 27,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": 11668,
          "Prezzo": 21,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 43,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Kraeff, Mr. Theodor",
          "Sesso": "male",
          "Età": null,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 349253,
          "Prezzo": 7.8958,
          "Cabina": null,
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 44,
          "Sopravvissuto": 1,
          "Classe": 2,
          "Nome": "Laroche, Miss. Simonne Marie Anne Andree",
          "Sesso": "female",
          "Età": 3,
          "Parenti a bordo": 3,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 2,
          "Biglietto": "SC/Paris 2123",
          "Prezzo": 41.5792,
          "Cabina": null,
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 45,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "Devaney, Miss. Margaret Delia",
          "Sesso": "female",
          "Età": 19,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 330958,
          "Prezzo": 7.8792,
          "Cabina": null,
          "Imbarcato": "Q"
        },
        {
          "Id passeggero": 46,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Rogers, Mr. William John",
          "Sesso": "male",
          "Età": null,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": "S.C./A.4. 23567",
          "Prezzo": 8.05,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 47,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Lennon, Mr. Denis",
          "Sesso": "male",
          "Età": null,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": 370371,
          "Prezzo": 15.5,
          "Cabina": null,
          "Imbarcato": "Q"
        },
        {
          "Id passeggero": 48,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "O'Driscoll, Miss. Bridget",
          "Sesso": "female",
          "Età": null,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 14311,
          "Prezzo": 7.75,
          "Cabina": null,
          "Imbarcato": "Q"
        },
        {
          "Id passeggero": 49,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Samaan, Mr. Youssef",
          "Sesso": "male",
          "Età": null,
          "Parenti a bordo": 2,
          "Fratelli o consorti a bordo": 2,
          "Genitori o figli a bordo": 0,
          "Biglietto": 2662,
          "Prezzo": 21.6792,
          "Cabina": null,
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 50,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Arnold-Franchi, Mrs. Josef (Josefine Franchi)",
          "Sesso": "female",
          "Età": 18,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": 349237,
          "Prezzo": 17.8,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 51,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Panula, Master. Juha Niilo",
          "Sesso": "male",
          "Età": 7,
          "Parenti a bordo": 5,
          "Fratelli o consorti a bordo": 4,
          "Genitori o figli a bordo": 1,
          "Biglietto": 3101295,
          "Prezzo": 39.6875,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 52,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Nosworthy, Mr. Richard Cater",
          "Sesso": "male",
          "Età": 21,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": "A/4. 39886",
          "Prezzo": 7.8,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 53,
          "Sopravvissuto": 1,
          "Classe": 1,
          "Nome": "Harper, Mrs. Henry Sleeper (Myna Haxtun)",
          "Sesso": "female",
          "Età": 49,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": "PC 17572",
          "Prezzo": 76.7292,
          "Cabina": "D33",
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 54,
          "Sopravvissuto": 1,
          "Classe": 2,
          "Nome": "Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)",
          "Sesso": "female",
          "Età": 29,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": 2926,
          "Prezzo": 26,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 55,
          "Sopravvissuto": 0,
          "Classe": 1,
          "Nome": "Ostby, Mr. Engelhart Cornelius",
          "Sesso": "male",
          "Età": 65,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 1,
          "Biglietto": 113509,
          "Prezzo": 61.9792,
          "Cabina": "B30",
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 56,
          "Sopravvissuto": 1,
          "Classe": 1,
          "Nome": "Woolner, Mr. Hugh",
          "Sesso": "male",
          "Età": null,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 19947,
          "Prezzo": 35.5,
          "Cabina": "C52",
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 57,
          "Sopravvissuto": 1,
          "Classe": 2,
          "Nome": "Rugg, Miss. Emily",
          "Sesso": "female",
          "Età": 21,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": "C.A. 31026",
          "Prezzo": 10.5,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 58,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Novel, Mr. Mansouer",
          "Sesso": "male",
          "Età": 28.5,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 2697,
          "Prezzo": 7.2292,
          "Cabina": null,
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 59,
          "Sopravvissuto": 1,
          "Classe": 2,
          "Nome": "West, Miss. Constance Mirium",
          "Sesso": "female",
          "Età": 5,
          "Parenti a bordo": 3,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 2,
          "Biglietto": "C.A. 34651",
          "Prezzo": 27.75,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 60,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Goodwin, Master. William Frederick",
          "Sesso": "male",
          "Età": 11,
          "Parenti a bordo": 7,
          "Fratelli o consorti a bordo": 5,
          "Genitori o figli a bordo": 2,
          "Biglietto": "CA 2144",
          "Prezzo": 46.9,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 61,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Sirayanian, Mr. Orsen",
          "Sesso": "male",
          "Età": 22,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 2669,
          "Prezzo": 7.2292,
          "Cabina": null,
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 62,
          "Sopravvissuto": 1,
          "Classe": 1,
          "Nome": "Icard, Miss. Amelie",
          "Sesso": "female",
          "Età": 38,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 113572,
          "Prezzo": 80,
          "Cabina": "B28",
          "Imbarcato": null
        },
        {
          "Id passeggero": 63,
          "Sopravvissuto": 0,
          "Classe": 1,
          "Nome": "Harris, Mr. Henry Birkhardt",
          "Sesso": "male",
          "Età": 45,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": 36973,
          "Prezzo": 83.475,
          "Cabina": "C83",
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 64,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Skoog, Master. Harald",
          "Sesso": "male",
          "Età": 4,
          "Parenti a bordo": 5,
          "Fratelli o consorti a bordo": 3,
          "Genitori o figli a bordo": 2,
          "Biglietto": 347088,
          "Prezzo": 27.9,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 65,
          "Sopravvissuto": 0,
          "Classe": 1,
          "Nome": "Stewart, Mr. Albert A",
          "Sesso": "male",
          "Età": null,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": "PC 17605",
          "Prezzo": 27.7208,
          "Cabina": null,
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 66,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "Moubarek, Master. Gerios",
          "Sesso": "male",
          "Età": null,
          "Parenti a bordo": 2,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 1,
          "Biglietto": 2661,
          "Prezzo": 15.2458,
          "Cabina": null,
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 67,
          "Sopravvissuto": 1,
          "Classe": 2,
          "Nome": "Nye, Mrs. (Elizabeth Ramell)",
          "Sesso": "female",
          "Età": 29,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": "C.A. 29395",
          "Prezzo": 10.5,
          "Cabina": "F33",
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 68,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Crease, Mr. Ernest James",
          "Sesso": "male",
          "Età": 19,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": "S.P. 3464",
          "Prezzo": 8.1583,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 69,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "Andersson, Miss. Erna Alexandra",
          "Sesso": "female",
          "Età": 17,
          "Parenti a bordo": 6,
          "Fratelli o consorti a bordo": 4,
          "Genitori o figli a bordo": 2,
          "Biglietto": 3101281,
          "Prezzo": 7.925,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 70,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Kink, Mr. Vincenz",
          "Sesso": "male",
          "Età": 26,
          "Parenti a bordo": 2,
          "Fratelli o consorti a bordo": 2,
          "Genitori o figli a bordo": 0,
          "Biglietto": 315151,
          "Prezzo": 8.6625,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 71,
          "Sopravvissuto": 0,
          "Classe": 2,
          "Nome": "Jenkin, Mr. Stephen Curnow",
          "Sesso": "male",
          "Età": 32,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": "C.A. 33111",
          "Prezzo": 10.5,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 72,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Goodwin, Miss. Lillian Amy",
          "Sesso": "female",
          "Età": 16,
          "Parenti a bordo": 7,
          "Fratelli o consorti a bordo": 5,
          "Genitori o figli a bordo": 2,
          "Biglietto": "CA 2144",
          "Prezzo": 46.9,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 73,
          "Sopravvissuto": 0,
          "Classe": 2,
          "Nome": "Hood, Mr. Ambrose Jr",
          "Sesso": "male",
          "Età": 21,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": "S.O.C. 14879",
          "Prezzo": 73.5,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 74,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Chronopoulos, Mr. Apostolos",
          "Sesso": "male",
          "Età": 26,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": 2680,
          "Prezzo": 14.4542,
          "Cabina": null,
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 75,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "Bing, Mr. Lee",
          "Sesso": "male",
          "Età": 32,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 1601,
          "Prezzo": 56.4958,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 76,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Moen, Mr. Sigurd Hansen",
          "Sesso": "male",
          "Età": 25,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 348123,
          "Prezzo": 7.65,
          "Cabina": "F G73",
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 77,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Staneff, Mr. Ivan",
          "Sesso": "male",
          "Età": null,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 349208,
          "Prezzo": 7.8958,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 78,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Moutal, Mr. Rahamin Haim",
          "Sesso": "male",
          "Età": null,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 374746,
          "Prezzo": 8.05,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 79,
          "Sopravvissuto": 1,
          "Classe": 2,
          "Nome": "Caldwell, Master. Alden Gates",
          "Sesso": "male",
          "Età": 0.83,
          "Parenti a bordo": 2,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 2,
          "Biglietto": 248738,
          "Prezzo": 29,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 80,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "Dowdell, Miss. Elizabeth",
          "Sesso": "female",
          "Età": 30,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 364516,
          "Prezzo": 12.475,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 81,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Waelens, Mr. Achille",
          "Sesso": "male",
          "Età": 22,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 345767,
          "Prezzo": 9,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 82,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "Sheerlinck, Mr. Jan Baptist",
          "Sesso": "male",
          "Età": 29,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 345779,
          "Prezzo": 9.5,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 83,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "McDermott, Miss. Brigdet Delia",
          "Sesso": "female",
          "Età": null,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 330932,
          "Prezzo": 7.7875,
          "Cabina": null,
          "Imbarcato": "Q"
        },
        {
          "Id passeggero": 84,
          "Sopravvissuto": 0,
          "Classe": 1,
          "Nome": "Carrau, Mr. Francisco M",
          "Sesso": "male",
          "Età": 28,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 113059,
          "Prezzo": 47.1,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 85,
          "Sopravvissuto": 1,
          "Classe": 2,
          "Nome": "Ilett, Miss. Bertha",
          "Sesso": "female",
          "Età": 17,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": "SO/C 14885",
          "Prezzo": 10.5,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 86,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)",
          "Sesso": "female",
          "Età": 33,
          "Parenti a bordo": 3,
          "Fratelli o consorti a bordo": 3,
          "Genitori o figli a bordo": 0,
          "Biglietto": 3101278,
          "Prezzo": 15.85,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 87,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Ford, Mr. William Neal",
          "Sesso": "male",
          "Età": 16,
          "Parenti a bordo": 4,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 3,
          "Biglietto": "W./C. 6608",
          "Prezzo": 34.375,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 88,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Slocovski, Mr. Selman Francis",
          "Sesso": "male",
          "Età": null,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": "SOTON/OQ 392086",
          "Prezzo": 8.05,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 89,
          "Sopravvissuto": 1,
          "Classe": 1,
          "Nome": "Fortune, Miss. Mabel Helen",
          "Sesso": "female",
          "Età": 23,
          "Parenti a bordo": 5,
          "Fratelli o consorti a bordo": 3,
          "Genitori o figli a bordo": 2,
          "Biglietto": 19950,
          "Prezzo": 263,
          "Cabina": "C23 C25 C27",
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 90,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Celotti, Mr. Francesco",
          "Sesso": "male",
          "Età": 24,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 343275,
          "Prezzo": 8.05,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 91,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Christmann, Mr. Emil",
          "Sesso": "male",
          "Età": 29,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 343276,
          "Prezzo": 8.05,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 92,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Andreasson, Mr. Paul Edvin",
          "Sesso": "male",
          "Età": 20,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 347466,
          "Prezzo": 7.8542,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 93,
          "Sopravvissuto": 0,
          "Classe": 1,
          "Nome": "Chaffee, Mr. Herbert Fuller",
          "Sesso": "male",
          "Età": 46,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": "W.E.P. 5734",
          "Prezzo": 61.175,
          "Cabina": "E31",
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 94,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Dean, Mr. Bertram Frank",
          "Sesso": "male",
          "Età": 26,
          "Parenti a bordo": 3,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 2,
          "Biglietto": "C.A. 2315",
          "Prezzo": 20.575,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 95,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Coxon, Mr. Daniel",
          "Sesso": "male",
          "Età": 59,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 364500,
          "Prezzo": 7.25,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 96,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Shorney, Mr. Charles Joseph",
          "Sesso": "male",
          "Età": null,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 374910,
          "Prezzo": 8.05,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 97,
          "Sopravvissuto": 0,
          "Classe": 1,
          "Nome": "Goldschmidt, Mr. George B",
          "Sesso": "male",
          "Età": 71,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": "PC 17754",
          "Prezzo": 34.6542,
          "Cabina": "A5",
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 98,
          "Sopravvissuto": 1,
          "Classe": 1,
          "Nome": "Greenfield, Mr. William Bertram",
          "Sesso": "male",
          "Età": 23,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 1,
          "Biglietto": "PC 17759",
          "Prezzo": 63.3583,
          "Cabina": "D10 D12",
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 99,
          "Sopravvissuto": 1,
          "Classe": 2,
          "Nome": "Doling, Mrs. John T (Ada Julia Bone)",
          "Sesso": "female",
          "Età": 34,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 1,
          "Biglietto": 231919,
          "Prezzo": 23,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 100,
          "Sopravvissuto": 0,
          "Classe": 2,
          "Nome": "Kantor, Mr. Sinai",
          "Sesso": "male",
          "Età": 34,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": 244367,
          "Prezzo": 26,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 101,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Petranec, Miss. Matilda",
          "Sesso": "female",
          "Età": 28,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 349245,
          "Prezzo": 7.8958,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 102,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Petroff, Mr. Pastcho (\"Pentcho\")",
          "Sesso": "male",
          "Età": null,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 349215,
          "Prezzo": 7.8958,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 103,
          "Sopravvissuto": 0,
          "Classe": 1,
          "Nome": "White, Mr. Richard Frasar",
          "Sesso": "male",
          "Età": 21,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 1,
          "Biglietto": 35281,
          "Prezzo": 77.2875,
          "Cabina": "D26",
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 104,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Johansson, Mr. Gustaf Joel",
          "Sesso": "male",
          "Età": 33,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 7540,
          "Prezzo": 8.6542,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 105,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Gustafsson, Mr. Anders Vilhelm",
          "Sesso": "male",
          "Età": 37,
          "Parenti a bordo": 2,
          "Fratelli o consorti a bordo": 2,
          "Genitori o figli a bordo": 0,
          "Biglietto": 3101276,
          "Prezzo": 7.925,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 106,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Mionoff, Mr. Stoytcho",
          "Sesso": "male",
          "Età": 28,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 349207,
          "Prezzo": 7.8958,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 107,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "Salkjelsvik, Miss. Anna Kristine",
          "Sesso": "female",
          "Età": 21,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 343120,
          "Prezzo": 7.65,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 108,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "Moss, Mr. Albert Johan",
          "Sesso": "male",
          "Età": null,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 312991,
          "Prezzo": 7.775,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 109,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Rekic, Mr. Tido",
          "Sesso": "male",
          "Età": 38,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 349249,
          "Prezzo": 7.8958,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 110,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "Moran, Miss. Bertha",
          "Sesso": "female",
          "Età": null,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": 371110,
          "Prezzo": 24.15,
          "Cabina": null,
          "Imbarcato": "Q"
        },
        {
          "Id passeggero": 111,
          "Sopravvissuto": 0,
          "Classe": 1,
          "Nome": "Porter, Mr. Walter Chamberlain",
          "Sesso": "male",
          "Età": 47,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 110465,
          "Prezzo": 52,
          "Cabina": "C110",
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 112,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Zabour, Miss. Hileni",
          "Sesso": "female",
          "Età": 14.5,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": 2665,
          "Prezzo": 14.4542,
          "Cabina": null,
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 113,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Barton, Mr. David John",
          "Sesso": "male",
          "Età": 22,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 324669,
          "Prezzo": 8.05,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 114,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Jussila, Miss. Katriina",
          "Sesso": "female",
          "Età": 20,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": 4136,
          "Prezzo": 9.825,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 115,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Attalah, Miss. Malake",
          "Sesso": "female",
          "Età": 17,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 2627,
          "Prezzo": 14.4583,
          "Cabina": null,
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 116,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Pekoniemi, Mr. Edvard",
          "Sesso": "male",
          "Età": 21,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": "STON/O 2. 3101294",
          "Prezzo": 7.925,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 117,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Connors, Mr. Patrick",
          "Sesso": "male",
          "Età": 70.5,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 370369,
          "Prezzo": 7.75,
          "Cabina": null,
          "Imbarcato": "Q"
        },
        {
          "Id passeggero": 118,
          "Sopravvissuto": 0,
          "Classe": 2,
          "Nome": "Turpin, Mr. William John Robert",
          "Sesso": "male",
          "Età": 29,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": 11668,
          "Prezzo": 21,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 119,
          "Sopravvissuto": 0,
          "Classe": 1,
          "Nome": "Baxter, Mr. Quigg Edmond",
          "Sesso": "male",
          "Età": 24,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 1,
          "Biglietto": "PC 17558",
          "Prezzo": 247.5208,
          "Cabina": "B58 B60",
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 120,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Andersson, Miss. Ellis Anna Maria",
          "Sesso": "female",
          "Età": 2,
          "Parenti a bordo": 6,
          "Fratelli o consorti a bordo": 4,
          "Genitori o figli a bordo": 2,
          "Biglietto": 347082,
          "Prezzo": 31.275,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 121,
          "Sopravvissuto": 0,
          "Classe": 2,
          "Nome": "Hickman, Mr. Stanley George",
          "Sesso": "male",
          "Età": 21,
          "Parenti a bordo": 2,
          "Fratelli o consorti a bordo": 2,
          "Genitori o figli a bordo": 0,
          "Biglietto": "S.O.C. 14879",
          "Prezzo": 73.5,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 122,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Moore, Mr. Leonard Charles",
          "Sesso": "male",
          "Età": null,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": "A4. 54510",
          "Prezzo": 8.05,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 123,
          "Sopravvissuto": 0,
          "Classe": 2,
          "Nome": "Nasser, Mr. Nicholas",
          "Sesso": "male",
          "Età": 32.5,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": 237736,
          "Prezzo": 30.0708,
          "Cabina": null,
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 124,
          "Sopravvissuto": 1,
          "Classe": 2,
          "Nome": "Webber, Miss. Susan",
          "Sesso": "female",
          "Età": 32.5,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 27267,
          "Prezzo": 13,
          "Cabina": "E101",
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 125,
          "Sopravvissuto": 0,
          "Classe": 1,
          "Nome": "White, Mr. Percival Wayland",
          "Sesso": "male",
          "Età": 54,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 1,
          "Biglietto": 35281,
          "Prezzo": 77.2875,
          "Cabina": "D26",
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 126,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "Nicola-Yarred, Master. Elias",
          "Sesso": "male",
          "Età": 12,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": 2651,
          "Prezzo": 11.2417,
          "Cabina": null,
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 127,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "McMahon, Mr. Martin",
          "Sesso": "male",
          "Età": null,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 370372,
          "Prezzo": 7.75,
          "Cabina": null,
          "Imbarcato": "Q"
        },
        {
          "Id passeggero": 128,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "Madsen, Mr. Fridtjof Arne",
          "Sesso": "male",
          "Età": 24,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": "C 17369",
          "Prezzo": 7.1417,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 129,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "Peter, Miss. Anna",
          "Sesso": "female",
          "Età": null,
          "Parenti a bordo": 2,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 1,
          "Biglietto": 2668,
          "Prezzo": 22.3583,
          "Cabina": "F E69",
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 130,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Ekstrom, Mr. Johan",
          "Sesso": "male",
          "Età": 45,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 347061,
          "Prezzo": 6.975,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 131,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Drazenoic, Mr. Jozef",
          "Sesso": "male",
          "Età": 33,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 349241,
          "Prezzo": 7.8958,
          "Cabina": null,
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 132,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Coelho, Mr. Domingos Fernandeo",
          "Sesso": "male",
          "Età": 20,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": "SOTON/O.Q. 3101307",
          "Prezzo": 7.05,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 133,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Robins, Mrs. Alexander A (Grace Charity Laury)",
          "Sesso": "female",
          "Età": 47,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": "A/5. 3337",
          "Prezzo": 14.5,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 134,
          "Sopravvissuto": 1,
          "Classe": 2,
          "Nome": "Weisz, Mrs. Leopold (Mathilde Francoise Pede)",
          "Sesso": "female",
          "Età": 29,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": 228414,
          "Prezzo": 26,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 135,
          "Sopravvissuto": 0,
          "Classe": 2,
          "Nome": "Sobey, Mr. Samuel James Hayden",
          "Sesso": "male",
          "Età": 25,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": "C.A. 29178",
          "Prezzo": 13,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 136,
          "Sopravvissuto": 0,
          "Classe": 2,
          "Nome": "Richard, Mr. Emile",
          "Sesso": "male",
          "Età": 23,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": "SC/PARIS 2133",
          "Prezzo": 15.0458,
          "Cabina": null,
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 137,
          "Sopravvissuto": 1,
          "Classe": 1,
          "Nome": "Newsom, Miss. Helen Monypeny",
          "Sesso": "female",
          "Età": 19,
          "Parenti a bordo": 2,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 2,
          "Biglietto": 11752,
          "Prezzo": 26.2833,
          "Cabina": "D47",
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 138,
          "Sopravvissuto": 0,
          "Classe": 1,
          "Nome": "Futrelle, Mr. Jacques Heath",
          "Sesso": "male",
          "Età": 37,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": 113803,
          "Prezzo": 53.1,
          "Cabina": "C123",
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 139,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Osen, Mr. Olaf Elon",
          "Sesso": "male",
          "Età": 16,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 7534,
          "Prezzo": 9.2167,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 140,
          "Sopravvissuto": 0,
          "Classe": 1,
          "Nome": "Giglio, Mr. Victor",
          "Sesso": "male",
          "Età": 24,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": "PC 17593",
          "Prezzo": 79.2,
          "Cabina": "B86",
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 141,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Boulos, Mrs. Joseph (Sultana)",
          "Sesso": "female",
          "Età": null,
          "Parenti a bordo": 2,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 2,
          "Biglietto": 2678,
          "Prezzo": 15.2458,
          "Cabina": null,
          "Imbarcato": "C"
        },
        {
          "Id passeggero": 142,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "Nysten, Miss. Anna Sofia",
          "Sesso": "female",
          "Età": 22,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 347081,
          "Prezzo": 7.75,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 143,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)",
          "Sesso": "female",
          "Età": 24,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": "STON/O2. 3101279",
          "Prezzo": 15.85,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 144,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Burke, Mr. Jeremiah",
          "Sesso": "male",
          "Età": 19,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 365222,
          "Prezzo": 6.75,
          "Cabina": null,
          "Imbarcato": "Q"
        },
        {
          "Id passeggero": 145,
          "Sopravvissuto": 0,
          "Classe": 2,
          "Nome": "Andrew, Mr. Edgardo Samuel",
          "Sesso": "male",
          "Età": 18,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 231945,
          "Prezzo": 11.5,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 146,
          "Sopravvissuto": 0,
          "Classe": 2,
          "Nome": "Nicholls, Mr. Joseph Charles",
          "Sesso": "male",
          "Età": 19,
          "Parenti a bordo": 2,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 1,
          "Biglietto": "C.A. 33112",
          "Prezzo": 36.75,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 147,
          "Sopravvissuto": 1,
          "Classe": 3,
          "Nome": "Andersson, Mr. August Edvard (\"Wennerstrom\")",
          "Sesso": "male",
          "Età": 27,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 350043,
          "Prezzo": 7.7958,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 148,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Ford, Miss. Robina Maggie \"Ruby\"",
          "Sesso": "female",
          "Età": 9,
          "Parenti a bordo": 4,
          "Fratelli o consorti a bordo": 2,
          "Genitori o figli a bordo": 2,
          "Biglietto": "W./C. 6608",
          "Prezzo": 34.375,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 149,
          "Sopravvissuto": 0,
          "Classe": 2,
          "Nome": "Navratil, Mr. Michel (\"Louis M Hoffman\")",
          "Sesso": "male",
          "Età": 36.5,
          "Parenti a bordo": 2,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 2,
          "Biglietto": 230080,
          "Prezzo": 26,
          "Cabina": "F2",
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 150,
          "Sopravvissuto": 0,
          "Classe": 2,
          "Nome": "Byles, Rev. Thomas Roussel Davids",
          "Sesso": "male",
          "Età": 42,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": 244310,
          "Prezzo": 13,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 151,
          "Sopravvissuto": 0,
          "Classe": 2,
          "Nome": "Bateman, Rev. Robert James",
          "Sesso": "male",
          "Età": 51,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": "S.O.P. 1166",
          "Prezzo": 12.525,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 152,
          "Sopravvissuto": 1,
          "Classe": 1,
          "Nome": "Pears, Mrs. Thomas (Edith Wearne)",
          "Sesso": "female",
          "Età": 22,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 1,
          "Genitori o figli a bordo": 0,
          "Biglietto": 113776,
          "Prezzo": 66.6,
          "Cabina": "C2",
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 153,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Meo, Mr. Alfonzo",
          "Sesso": "male",
          "Età": 55.5,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": "A.5. 11206",
          "Prezzo": 8.05,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 154,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "van Billiard, Mr. Austin Blyler",
          "Sesso": "male",
          "Età": 40.5,
          "Parenti a bordo": 2,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 2,
          "Biglietto": "A/5. 851",
          "Prezzo": 14.5,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 155,
          "Sopravvissuto": 0,
          "Classe": 3,
          "Nome": "Olsen, Mr. Ole Martin",
          "Sesso": "male",
          "Età": null,
          "Parenti a bordo": 0,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 0,
          "Biglietto": "Fa 265302",
          "Prezzo": 7.3125,
          "Cabina": null,
          "Imbarcato": "S"
        },
        {
          "Id passeggero": 156,
          "Sopravvissuto": 0,
          "Classe": 1,
          "Nome": "Williams, Mr. Charles Duane",
          "Sesso": "male",
          "Età": 51,
          "Parenti a bordo": 1,
          "Fratelli o consorti a bordo": 0,
          "Genitori o figli a bordo": 1,
          "Biglietto": "PC 17597",
          "Prezzo": 61.3792,
          "Cabina": null,
          "Imbarcato": "C"
        },
        {
          "Id passeggero": null
        }
      ],
      "parsedMeta": {
        "delimiter": "\t",
        "linebreak": "\n",
        "aborted": false,
        "truncated": false,
        "cursor": 10714,
        "fields": [
          "Id passeggero",
          "Sopravvissuto",
          "Classe",
          "Nome",
          "Sesso",
          "Età",
          "Parenti a bordo",
          "Fratelli o consorti a bordo",
          "Genitori o figli a bordo",
          "Biglietto",
          "Prezzo",
          "Cabina",
          "Imbarcato"
        ],
        "expandedMetaFields": {
          "Id passeggero": "number",
          "Sopravvissuto": "number",
          "Classe": "number",
          "Nome": "category",
          "Sesso": "category",
          "Età": "number",
          "Parenti a bordo": "number",
          "Fratelli o consorti a bordo": "number",
          "Genitori o figli a bordo": "number",
          "Biglietto": "category",
          "Prezzo": "number",
          "Cabina": "category",
          "Imbarcato": "category"
        }
      },
      "variableOnXaxis": "Prezzo",
      "variableOnYaxis": "Età",
      "showDistribution": false
    }
}

export default initialState